sudo: required
services:
  - docker
before_install:
  - docker pull nikitab/dockergrader-testcompile
  - docker pull ubuntu
language: python
python:
  - "3.5"
  - "3.4"
install: pip install tox
script:
  - tox
